Unable to access network causes this test to fail
```
main/test-foundation-networking-fetch.swift:5: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=256 "(null)"
Current stack trace:
0    libswiftCore.so                    0x00007f00432741d0 swift_reportError + 50
1    libswiftCore.so                    0x00007f00432e9180 _swift_stdlib_reportFatalErrorInFile + 109
2    libswiftCore.so                    0x00007f0042fcf580 _assertionFailure(_:_:file:line:flags:) + 1169
3    libswiftCore.so                    0x00007f0043023740 swift_unexpectedError + 995
4    test-foundation-networking-fetch   0x000055b33fe5c692 <unavailable> + 5778
5    libc.so.6                          0x00007f0042265fc0 __libc_start_main + 243
6    test-foundation-networking-fetch   0x000055b33fe5c21e <unavailable> + 4638

error: command failed with exit status: -4
```